on:
  workflow_call:
    inputs:
      artifact-name:
        required: false
        type: string
      artifact-pattern:
        required: false
        type: string
        default: sonarqube-report-*
      sarif-report-path:
        required: false
        type: string
      python-coverage-report-path:
        required: false
        type: string

jobs:
  sonar:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Report Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: ${{ inputs.artifact-pattern }}
          name: ${{ inputs.artifact-name }}
      - run: ls -la
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.sarifReportPaths=${{ inputs.sarif-report-path }}
            -Dsonar.python.coverage.reportPaths=${{ inputs.python-coverage-report-path }}
